const GET_VIDEOGAMES = "GET_VIDEOGAMES"
const GET_GENRES = "GET_GENRES"
const POST_VIDEOGAME = "POST_VIDEOGAME"
const GET_PLATFORMS = "GET_PLATFORMS"
const GET_NAME = "GET_NAME"


export {GET_VIDEOGAMES, GET_GENRES, POST_VIDEOGAME, GET_PLATFORMS, GET_NAME }